config/routes.rb
Rails.application.routes.draw do
  get 'diagnoses/new'
  get 'diagnoses/index'
  resources :games
  root "games#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :tag_games_rerationships, dependent: :destroy
  has_many :tags, through: :tag_games_rerationships, dependent: :destroy
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_games_rerationships, dependent: :destroy
  has_many :games, through: :tag_games_rerationships, dependent: :destroy
end

app/models/tag_games_rerationship.rb
class TagGamesRerationship < ApplicationRecord
  belongs_to :game
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/diagnoses_controller.rb
class DiagnosesController < ApplicationController
  def new
  end

  def index
    games = Game.all
    selected_tag_ids = params[:answer]
    @mach_tag_count = 0
    tmp_mach_tag_count = 0
    @mached_games = []

    games.each do |game|
      tmp_mach_tag_count = 0
      game.tags.each do |tag|
        if selected_tag_ids&.include?(tag.id.to_s)
          tmp_mach_tag_count = tmp_mach_tag_count + 1 
        end
      end

      if @mach_tag_count < tmp_mach_tag_count
        @mached_games = []
        @mached_games << game
        @mach_tag_count = tmp_mach_tag_count
      elsif @mach_tag_count == tmp_mach_tag_count
        @mached_games << game
      end
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]

  # GET /games or /games.json
  def index
    @games = Game.all
  end

  # GET /games/1 or /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games or /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to game_url(@game), notice: "Game was successfully created." }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to game_url(@game), notice: "Game was successfully updated." }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:name, :discription, tag_ids: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diagnoses_helper.rb
module DiagnosesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/diagnoses/index.html.erb
<h1>Diagnoses#index</h1>
<p>Find me in app/views/diagnoses/index.html.erb</p>

マッチ度：
<%= @mach_tag_count.to_f / params[:answer].length.to_f * 100 %> %

<% @mached_games.each do |game| %>
  <div class="game-container">
    Game名:<%= game.name %><br>
    説明:<%= game.discription %><br>
    タグ:
    <% game.tags.each do |tag| %>
      <%= tag.name %>
    <% end %>
  </div>
<% end %>

<%= link_to "診断へ", diagnoses_new_path %>
<%= link_to "New game", new_game_path %>

app/views/diagnoses/new.html.erb
<h1>Diagnoses#new</h1>
<p>Find me in app/views/diagnoses/new.html.erb</p>

<% tags = Tag.select(&:name) %>
<% questions = [
  {title: "何人で遊びますか？", number: 4},
  {title: "誰と遊びますか？", number: 3},
  {title: "シチュエーションは？", number: 4},
  {title: "遊ぶ人の世代は？", number: 3},
  {title: "プレイ時間は？", number: 3},
  {title: "ゲームの種類は?", number: 12},
] %>
<% question_id = 1 %>

<%= form_tag diagnoses_index_path, method: :get do %>
  <% questions.each do |q| %>
    <div class="question-container">
      <%= q[:title] %>
      <% tags.shift(q[:number]).each do |t| %>
        <input type="checkbox" id="checkbox<%= question_id %>" name="answer[]" value="<%= question_id %>" >
        <label for="checkbox<%= question_id %>"><%= t.name %></label>
        <% question_id += 1 %>
      <% end %>
    </div>
  <% end %>
  <%= submit_tag %>
<% end %>

app/views/games/_form.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :discription, style: "display: block" %>
    <%= form.text_area :discription %>
  </div>

  <div class='form-group'>
    <%= form.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
      <div class='form-check'>
        <%= tag.label class: 'form-check-label' do %>
          <%= tag.check_box class: 'form-check-input' %>
          <%= tag.text %>
        <% end %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/games/_game.html.erb
<div id="<%= dom_id game %>">
  <p>
    <strong>Name:</strong>
    <%= game.name %>
  </p>

  <p>
    <strong>Discription:</strong>
    <%= game.discription %>
  </p>

  <% game.tags.each do |tag| %>
    <span><%= tag.name %></span>
  <% end %>

</div>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Show this game", @game %> |
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/index.html.erb
<p style="color: green"><%= notice %></p>
<%= link_to "診断へ", diagnoses_new_path %>
<h1>Games</h1>

<div id="games">
  <% @games.each do |game| %>
    <%= render game %>
    <p>
      <%= link_to "Show this game", game %>
    </p>
  <% end %>
</div>

<%= link_to "New game", new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @game %>

<div>
  <%= link_to "Edit this game", edit_game_path(@game) %> |
  <%= link_to "Back to games", games_path %>

  <%= button_to "Destroy this game", @game, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DiagnoseGames</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>